debug = true
log_level = "info"
channel_size = 100
tcp_port = "9997"
dtls_port = "9232"
grpc_port = "50051"
default_gateway = "128.32.37.48:9997"
[[ros]]
local = "pub"
node_name = "GDP_Router_for_chatter"
topic_name = "/chatter"
topic_type = "std_msgs/msg/String"
[[ros]]
local = "pub"
node_name = "GDP_Router_for_image"
topic_name = "/Image"
topic_type = "sensor_msgs/msg/CompressedImage"
[database]
url = "custom database url"
