debug = true
log_level = "info"
channel_size = 100
tcp_port = "9997"
dtls_port = "9232"
grpc_port = "50051"
peer_with_gateway = false
default_gateway = "128.32.37.55:9997"
[[ros]]
local = "pub"
node_name = "cloud_left_etch"
topic_name = "/action_left_etch"
topic_type = "std_msgs/msg/String"
[[ros]]
local = "pub"
node_name = "cloud_right_etch"
topic_name = "/action_right_etch"
topic_type = "std_msgs/msg/String"
[[ros]]
local = "sub"
node_name = "cloud_left_etch"
topic_name = "/image_left_etch"
topic_type = "sensor_msgs/msg/CompressedImage"
[[ros]]
local = "sub"
node_name = "cloud_right_etch"
topic_name = "/image_right_etch"
topic_type = "sensor_msgs/msg/CompressedImage"
[database]
url = "custom database url"
