debug = false
log_level = "info"
net_interface = "eno1"
ip_local = "128.32.37.48"
ip_gateway = "128.32.37.48"
router_port=31415
local_rib_path="/tmp/rib"
GDPNAME = 6
HAS_PARENT = false
REMOTE_RIB_ADDRESS = "127.0.0.1:0000"
REMOTE_RIB_NAME = 0
[database]
url = "custom database url"
