version: "3"

services:
    talker:
        restart: always
        build: 
          context: ./
          dockerfile: ./Dockerfile
        volumes:
          - "./src:/src" 
          - "./scripts:/scripts" 
        networks:
          vpcbr:
            ipv4_address: 10.5.0.5
        environment:
          SGC_CONFIG: "talker.toml"
          # SGC_CONFIG: "automatic.toml"
          # this connects the talker to the listener
          RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
          CYCLONEDDS_URI: "file:///fog_ws/cyclonedds.ubuntu.2204.xml"
        command: >
          bash -c "source /opt/ros/humble/setup.bash; 
          ros2 run demo_nodes_py talker & 
          /gdp-router router"
    listener:
        restart: always
        build: 
          context: ./
          dockerfile: ./Dockerfile
        volumes:
          - "./src:/src" 
          - "./scripts:/scripts" 
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6
        environment:
          SGC_CONFIG: "listener.toml"
          # SGC_CONFIG: "automatic.toml"
          GATEWAY_IP: "10.5.0.5"
          RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
          CYCLONEDDS_URI: "file:///fog_ws/cyclonedds.ubuntu.2204.xml"
        # TODO: this is a hack to make sure the subscriber is started after the publisher
        # will also test the scenario that is opposite
        depends_on:
          - talker 
        command: >
          bash -c "source /opt/ros/humble/setup.bash; 
          ros2 run demo_nodes_py listener & 
          /gdp-router router"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1