[package]
name = "core"
version = "2.0.0-beta"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "The application core code"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

rand = "0.8.4"
log = "0.4.14"
pnet= { version = "0.31.0", features = ["std"] }
pnet_macros_support =  { version = "0.31.0" }
pnet_macros ={ version = "0.31.0" }
pnet_packet = { version = "0.31.0", features = ["std"] }
local-ip-address = "0.4.9"
aes-gcm = "0.9.4"
anyhow = "1.0"